#!/bin/sh

# .githooks/pre-commit, pre commit hook for git to prompt refreshkeys
# source: https://github.com/pricheal/dotfiles

# if interactive
if tty -s
then

    # refreshkeys requires user input, which won't work without this for
    # some reason (source: https://stackoverflow.com/a/10015707)
    exec < /dev/tty

    # run refreshkeys (only if needed), commit aborted if this fails
    refreshkeys --if-needed

fi
