#!/bin/sh

# yank, script for yanking
# adapted from https://sunaku.github.io/tmux-yank-osc52.html
# to only do osc 52

input=$( cat "$@" )
input() { printf %s "$input" ;}

# copy via OSC 52
printf_escape() {
  esc=$1
  printf "$esc"
}

printf_escape "\033]52;c;$( input | base64 | tr -d '\r\n' )\a"
