#!/bin/bash

# .config/yadm/bootstrap, bootstraps dotfiles
# source: https://github.com/pricheal/dotfiles

# add 1password accounts if they don't exist
op account list | grep my.1password.com > /dev/null || op account add --address my.1password.com --email patrickricheal@gmail.com
op account list | grep fitdegree.1password.com > /dev/null || op account add --address fitdegree.1password.com --email patrick.richeal@fitdegree.com

# decrypt private keys
echo "Decrypting private keys with yadm"
yadm decrypt

# import gpg private key
echo "Importing gpg private key"
gpg --import ~/.gnupg/gpg-private.key

# generate key bindings for less
echo "Generating less key binds"
lesskey ~/.lesskey

# setup base16 shell
rm -rf ~/.config/base16-shell
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
shopt -s expand_aliases && eval "$(~/.config/base16-shell/profile_helper.sh)"
base16_default-dark && shopt -u expand_aliases

# install neovim plugins
nvim --headless +PlugInstall +qall

# set dotfiles repo remote to ssh
echo "Setting dotfiles repo remote to ssh"
yadm remote set-url origin git@github.com:pricheal/dotfiles.git

